package com.example.xingliansdk.network.api.weather.bean

data class WeatherBean(val code:String,
                       val updateTime:String,
                       val fxLink:String,
                       val daily:ArrayList<DayWeather>
)

data class DayWeather(val fxDate:String,
                      val sunrise:String,
                      val sunset:String,
                      val moonrise:String,
                      val moonset:String,
                      val moonPhase:String,
                      val tempMax:String,
                      val tempMin:String,
                      val iconDay:String,
                      val textDay:String,
                      val iconNight:String,
                      val textNight:String,
                      val wind360Day:String,
                      val windDirDay:String,
                      val windScaleDay:String,
                      val windSpeedDay:String,
                      val wind360Night:String,
                      val windDirNight:String,
                      val windScaleNight:String,
                      val windSpeedNight:String,
                      val humidity:String,
                      val precip:String,
                      val pressure:String,
                      val vis:String,
                      val cloud:String,
                      val uvIndex:String
)


//{
//	"code": "200",
//	"updateTime": "2021-03-30T10:35+08:00",
//	"fxLink": "http://hfx.link/1tjo1",
//	"daily": [{
//		"fxDate": "2021-03-30",
//		"sunrise": "05:59",
//		"sunset": "18:37",
//		"moonrise": "20:28",
//		"moonset": "07:02",
//		"moonPhase": "亏凸月",
//		"tempMax": "21",
//		"tempMin": "9",
//		"iconDay": "101",
//		"textDay": "多云",
//		"iconNight": "101",
//		"textNight": "多云",
//		"wind360Day": "180",
//		"windDirDay": "南风",
//		"windScaleDay": "3-4",
//		"windSpeedDay": "16",
//		"wind360Night": "225",
//		"windDirNight": "西南风",
//		"windScaleNight": "1-2",
//		"windSpeedNight": "3",
//		"humidity": "38",
//		"precip": "0.0",
//		"pressure": "1006",
//		"vis": "25",
//		"cloud": "1",
//		"uvIndex": "5"
//	}, {
//		"fxDate": "2021-03-31",
//		"sunrise": "05:57",
//		"sunset": "18:38",
//		"moonrise": "21:46",
//		"moonset": "07:34",
//		"moonPhase": "亏凸月",
//		"tempMax": "24",
//		"tempMin": "10",
//		"iconDay": "100",
//		"textDay": "晴",
//		"iconNight": "101",
//		"textNight": "多云",
//		"wind360Day": "45",
//		"windDirDay": "东北风",
//		"windScaleDay": "1-2",
//		"windSpeedDay": "3",
//		"wind360Night": "90",
//		"windDirNight": "东风",
//		"windScaleNight": "3-4",
//		"windSpeedNight": "16",
//		"humidity": "32",
//		"precip": "0.0",
//		"pressure": "1012",
//		"vis": "25",
//		"cloud": "0",
//		"uvIndex": "6"
//	}, {
//		"fxDate": "2021-04-01",
//		"sunrise": "05:56",
//		"sunset": "18:39",
//		"moonrise": "23:02",
//		"moonset": "08:09",
//		"moonPhase": "亏凸月",
//		"tempMax": "19",
//		"tempMin": "10",
//		"iconDay": "101",
//		"textDay": "多云",
//		"iconNight": "101",
//		"textNight": "多云",
//		"wind360Day": "90",
//		"windDirDay": "东风",
//		"windScaleDay": "1-2",
//		"windSpeedDay": "3",
//		"wind360Night": "90",
//		"windDirNight": "东风",
//		"windScaleNight": "1-2",
//		"windSpeedNight": "3",
//		"humidity": "66",
//		"precip": "0.0",
//		"pressure": "1013",
//		"vis": "24",
//		"cloud": "19",
//		"uvIndex": "3"
//	}],
//	"refer": {
//		"sources": ["Weather China"],
//		"license": ["no commercial use"]
//	}
//}